### ISSUE TITLE
models remain after cancelling job

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/kubernetes-jenkins#151]
Start a `test-cdk` job, let it start deploying stuff, then cancel it via the jenkins UI.

SSH to the jenkins master and you'll see the model is still there with `juju models -c jenkins-ci-<cloud>`.  I think we need to trap a few exit signals to make sure models are destroyed if the job is cancelled.

In `layer-cwr`, we trap the following and call a cleanup handler:
```
trap "$handler || true" EXIT SIGHUP SIGINT SIGTERM
```

Maybe something similar would work for us, probably around [temporary_model](https://github.com/juju-solutions/kubernetes-jenkins/blob/master/integration-tests/utils.py#L140), maybe with a tasteful `atexit`.

We could also just run a cleanup job every few hours looking for `cdk-build-upgrade-x` models that have not had a "Last connection" in X hours:

```
$ juju models -c jenkins-ci-aws
Controller: jenkins-ci-aws

Model       Cloud/Region   Status     Machines  Cores  Access  Last connection
controller  aws/us-east-1  available         1      2  admin   just now
cdk-build-upgrade-7961  aws/us-east-1  available         3     12  admin   2017-10-23
```

**Comment by kwmonroe** [comment]
I also find the `build-and-release-*` jobs quite offensive.  They do things like this:

```bash
  JUJU_CONTROLLER="jenkins-ci-${CLOUD}"
  juju switch ${JUJU_CONTROLLER}

  MODEL="build-and-release-etcd-${BUILD_NUMBER}"
  # Create a model just for this run of the tests.
  juju add-model ${MODEL}
  ...
  trap "juju destroy-model -y ${MODEL} || true" EXIT
```

The problem here is that the controller might change during execution of the job (either by an admin or some other job calling `juju switch`).  When this happens, `destroy-model` will be called on the wrong controller -- this will `fail || true`, so the job will still complete and no one but the accountant will be the wiser.

Fully qualify the trap with the controller name.

**Comment by battlemidget** [comment]
This will be further addressed when all jobs are moved into pipelines

**Comment by battlemidget** [comment]
All jobs are now in pipelines and cleanup is handled appropriately
