### ISSUE TITLE
auto merge from upstream use different user than 'root'

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/kubernetes-jenkins#230]
Currently, root is seen as the committer rather than someone like cdkbot. We should configure git to make use of the bots github account if available.

/cc @hyperbolic2346 Just keeping you in the loop, i plan on adding to this issue this week.

**Comment by hyperbolic2346** [comment]
We need to inject github credentials for the PR job, so that will probably help here since we'll have the secret in jenkins.

**Comment by battlemidget** [comment]
cdkbot is now the committer
