### ISSUE TITLE
What other bundles gets the full testing

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/kubernetes-jenkins#234]
Should the additional bundles we build go through the same range of testing we perform on cdk and kubernetes-core?

- canonical-kubernetes-elasticsearch
- kubernetes-calico
- canonical-kubernetes-canal

**Comment by tvansteenburgh** [comment]
@battlemidget Yes, goal should be to get tests in place for every bundle we publish (and also for GPU, as Kos mentioned). There are cards in the CI backlog for some of these things, but please add more for anything missing.n

**Comment by battlemidget** [comment]
Tests for all bundles ready, the release pipeline will only gate on k8s-core and cdk
