### ISSUE TITLE
microk8s arm testing takes 8+ hours

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/kubernetes-jenkins#279]
microk8s arm testing and releasing takes about 8 hours for one job to complete. Is it possible to trim this down some?

**Comment by ktsakalozos** [comment]
The tests should take less than 2 hours per distribution per track. We currently test on two distros and based on what is released upstream we may test upto 3 tracks (latest, 1.12, 1.13  - for amd64 we have additionally 1.10, 1.11). So you see how the time can pileup.

I am trying to consolidate many tests in the same testing cycle ( https://github.com/ubuntu/microk8s/pull/190 ) but eventually we will need to parallelise some of the tests internally eg tests tracks in parallel on separate slaves and/or tests distributions in parallel. It is not impossible, but needs a bit of thinking. Is it easy to get more slaves? This should guide the degree of parallelisation.

**Comment by battlemidget** [comment]
This has been resolved with a max timeout of 4hours
